### ISSUE TITLE
need a documentation for building the driver/library on our own

### ISSUE THREAD

**Issue by bhanuponguru** [datajake1999/SAPI5IBMTTS#3]
hey jake and other devs/contributers, please update the readme with the documentation for building the driver on our own. hohw please tell or reply me how to build.
of course, i have visual studio with desktop development with c++.
i tryed to open the dsp file with visual studio2019 and try to batch build and selecting debug and release optoins and bulding.
but i notice errors.
can you tell me the corect way or update the read me wit correct way for building?
thanks

**Comment by datajake1999** [comment]
I used Visual studio 6 to build this. You can get a copy of Visual Studio 6 with Included Microsoft Platform 2003 SDK from http://grossgang.com/utilities/vc6.7z
Extract the archive to the root of your C drive, and open a command prompt.
Next, type c:\vc6\vcvars32 followed by msdev. If you get any messages about program compatibility, you can just ignore them.

**Comment by bhanuponguru** [comment]
so, opening the dsp file with vc6 and building does the job, right?

**Comment by datajake1999** [comment]
Yes, that is correct. The needed speech SDK files are already included in the repo, so you shouldn't need to get anything else.

**Comment by bhanuponguru** [comment]
hey @datajake1999 
i did the same way as you told.
but it just said setting up to use microsoft c++ build tools.
and how to openit with vs6?
and one more thing, i don't wan't to switch back to vc6 just for compilation :D. so, will vc6 use seperately while keeping my latest vc buildtools came with vs2019? or will they bee replaced by vc6?
and, can you please tell me how to open that dsp file wiht vc6? when i open, it's opening with vs2019 and i cannot compile it.

**Comment by datajake1999** [comment]
after running the batch file, type msdev to launch the IDE, and then you can open the project file from their. Please let me know If you run into any further problems, and I will do my best to help you out.

**Comment by bhanuponguru** [comment]
hey @datajake1999 
i have one more question. will it replace my vc14 buildtools which i get from vs2019? or they both run parelelly?

**Comment by datajake1999** [comment]
It won't replace your newer build tools, as the batch file only sets
up the old tools for that command prompt session.

**Comment by bhanuponguru** [comment]
vo i din't know that. :D

**Comment by trypsynth** [comment]
We build with VC++6. Opening the dsp file in there should work.

**Comment by trypsynth** [comment]
oh I didn't notice it got resolved, because this issue was still open. Can you close it?
